{
  "compatibilityLevel": 1604,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "gold_ml_model_metrics",
        "columns": [
          {"name": "demo_id", "dataType": "string", "sourceColumn": "demo_id"},
          {"name": "use_case", "dataType": "string", "sourceColumn": "use_case"},
          {"name": "model_type", "dataType": "string", "sourceColumn": "model_type"},
          {"name": "feature_count", "dataType": "int64", "sourceColumn": "feature_count"},
          {"name": "train_rows", "dataType": "int64", "sourceColumn": "train_rows"},
          {"name": "test_rows", "dataType": "int64", "sourceColumn": "test_rows"},
          {"name": "auc_roc", "dataType": "double", "sourceColumn": "auc_roc"},
          {"name": "accuracy", "dataType": "double", "sourceColumn": "accuracy"},
          {"name": "f1_score", "dataType": "double", "sourceColumn": "f1_score"},
          {"name": "trained_at", "dataType": "dateTime", "sourceColumn": "trained_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_model_metrics",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Model AUC", "expression": "AVERAGE(gold_ml_model_metrics[auc_roc])", "formatString": "0.000"},
          {"name": "Model Accuracy", "expression": "AVERAGE(gold_ml_model_metrics[accuracy])", "formatString": "0.0%"},
          {"name": "F1 Score", "expression": "AVERAGE(gold_ml_model_metrics[f1_score])", "formatString": "0.000"},
          {"name": "Feature Count", "expression": "MAX(gold_ml_model_metrics[feature_count])", "formatString": "0"},
          {"name": "Training Rows", "expression": "MAX(gold_ml_model_metrics[train_rows])", "formatString": "#,##0"},
          {"name": "Test Rows", "expression": "MAX(gold_ml_model_metrics[test_rows])", "formatString": "#,##0"}
        ]
      },
      {
        "name": "gold_ml_feature_importance",
        "columns": [
          {"name": "feature", "dataType": "string", "sourceColumn": "feature"},
          {"name": "importance", "dataType": "double", "sourceColumn": "importance"},
          {"name": "model_timestamp", "dataType": "dateTime", "sourceColumn": "model_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_feature_importance",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Importance", "expression": "SUM(gold_ml_feature_importance[importance])", "formatString": "0.0000"}
        ]
      },
      {
        "name": "gold_ml_predictions",
        "columns": [
          {"name": "transaction_id", "dataType": "string", "sourceColumn": "transaction_id"},
          {"name": "account_id", "dataType": "string", "sourceColumn": "account_id"},
          {"name": "customer_id", "dataType": "string", "sourceColumn": "customer_id"},
          {"name": "transaction_date", "dataType": "dateTime", "sourceColumn": "transaction_date"},
          {"name": "merchant_category", "dataType": "string", "sourceColumn": "merchant_category"},
          {"name": "channel", "dataType": "string", "sourceColumn": "channel"},
          {"name": "country", "dataType": "string", "sourceColumn": "country"},
          {"name": "segment", "dataType": "string", "sourceColumn": "segment"},
          {"name": "region", "dataType": "string", "sourceColumn": "region"},
          {"name": "amount", "dataType": "double", "sourceColumn": "amount"},
          {"name": "had_fraud", "dataType": "int64", "sourceColumn": "had_fraud"},
          {"name": "predicted_fraud", "dataType": "int64", "sourceColumn": "predicted_fraud"},
          {"name": "fraud_probability", "dataType": "double", "sourceColumn": "fraud_probability"},
          {"name": "risk_level", "dataType": "string", "sourceColumn": "risk_level"},
          {"name": "scored_at", "dataType": "dateTime", "sourceColumn": "scored_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_predictions",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Predictions", "expression": "COUNTROWS(gold_ml_predictions)", "formatString": "#,##0"},
          {"name": "Predicted Fraud", "expression": "SUM(gold_ml_predictions[predicted_fraud])", "formatString": "#,##0"},
          {"name": "Actual Fraud", "expression": "SUM(gold_ml_predictions[had_fraud])", "formatString": "#,##0"},
          {"name": "Avg Fraud Probability", "expression": "AVERAGE(gold_ml_predictions[fraud_probability])", "formatString": "0.0%"},
          {"name": "Predicted Fraud Rate %", "expression": "DIVIDE(SUM(gold_ml_predictions[predicted_fraud]), COUNTROWS(gold_ml_predictions), 0) * 100", "formatString": "0.0"},
          {"name": "Total Amount", "expression": "SUM(gold_ml_predictions[amount])", "formatString": "\\$#,##0"}
        ]
      },
      {
        "name": "gold_ml_summary",
        "columns": [
          {"name": "merchant_category", "dataType": "string", "sourceColumn": "merchant_category"},
          {"name": "total_transactions", "dataType": "int64", "sourceColumn": "total_transactions"},
          {"name": "predicted_fraud_count", "dataType": "int64", "sourceColumn": "predicted_fraud_count"},
          {"name": "actual_fraud_count", "dataType": "int64", "sourceColumn": "actual_fraud_count"},
          {"name": "avg_fraud_probability", "dataType": "double", "sourceColumn": "avg_fraud_probability"},
          {"name": "total_amount", "dataType": "double", "sourceColumn": "total_amount"},
          {"name": "fraud_rate", "dataType": "double", "sourceColumn": "fraud_rate"},
          {"name": "overall_risk", "dataType": "string", "sourceColumn": "overall_risk"},
          {"name": "summary_timestamp", "dataType": "dateTime", "sourceColumn": "summary_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_summary",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Merchant Categories", "expression": "COUNTROWS(gold_ml_summary)", "formatString": "0"},
          {"name": "Avg Fraud Risk", "expression": "AVERAGE(gold_ml_summary[avg_fraud_probability])", "formatString": "0.0%"},
          {"name": "Avg Fraud Rate", "expression": "AVERAGE(gold_ml_summary[fraud_rate])", "formatString": "0.0"},
          {"name": "Total Predicted Fraud", "expression": "SUM(gold_ml_summary[predicted_fraud_count])", "formatString": "#,##0"},
          {"name": "High Risk Categories", "expression": "CALCULATE(COUNTROWS(gold_ml_summary), gold_ml_summary[overall_risk] = \"high\") + 0", "formatString": "0"}
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_predictions_summary",
        "fromTable": "gold_ml_predictions",
        "fromColumn": "merchant_category",
        "toTable": "gold_ml_summary",
        "toColumn": "merchant_category",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DatabaseQuery",
        "kind": "m",
        "expression": "let\n    database = Sql.Database(\"{{SQL_ENDPOINT}}\", \"{{LAKEHOUSE_NAME}}\")\nin\n    database"
      }
    ],
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"gold_ml_model_metrics\",\"gold_ml_feature_importance\",\"gold_ml_predictions\",\"gold_ml_summary\"]"}
    ]
  }
}
