{
  "compatibilityLevel": 1604,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "gold_ml_model_metrics",
        "columns": [
          {"name": "demo_id", "dataType": "string", "sourceColumn": "demo_id"},
          {"name": "use_case", "dataType": "string", "sourceColumn": "use_case"},
          {"name": "model_type", "dataType": "string", "sourceColumn": "model_type"},
          {"name": "feature_count", "dataType": "int64", "sourceColumn": "feature_count"},
          {"name": "train_rows", "dataType": "int64", "sourceColumn": "train_rows"},
          {"name": "test_rows", "dataType": "int64", "sourceColumn": "test_rows"},
          {"name": "auc_roc", "dataType": "double", "sourceColumn": "auc_roc"},
          {"name": "accuracy", "dataType": "double", "sourceColumn": "accuracy"},
          {"name": "f1_score", "dataType": "double", "sourceColumn": "f1_score"},
          {"name": "trained_at", "dataType": "dateTime", "sourceColumn": "trained_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_model_metrics",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Model AUC", "expression": "AVERAGE(gold_ml_model_metrics[auc_roc])", "formatString": "0.000"},
          {"name": "Model Accuracy", "expression": "AVERAGE(gold_ml_model_metrics[accuracy])", "formatString": "0.0%"},
          {"name": "F1 Score", "expression": "AVERAGE(gold_ml_model_metrics[f1_score])", "formatString": "0.000"},
          {"name": "Feature Count", "expression": "MAX(gold_ml_model_metrics[feature_count])", "formatString": "0"},
          {"name": "Training Rows", "expression": "MAX(gold_ml_model_metrics[train_rows])", "formatString": "#,##0"},
          {"name": "Test Rows", "expression": "MAX(gold_ml_model_metrics[test_rows])", "formatString": "#,##0"}
        ]
      },
      {
        "name": "gold_ml_feature_importance",
        "columns": [
          {"name": "feature", "dataType": "string", "sourceColumn": "feature"},
          {"name": "importance", "dataType": "double", "sourceColumn": "importance"},
          {"name": "model_timestamp", "dataType": "dateTime", "sourceColumn": "model_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_feature_importance",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Importance", "expression": "SUM(gold_ml_feature_importance[importance])", "formatString": "0.0000"}
        ]
      },
      {
        "name": "gold_ml_predictions",
        "columns": [
          {"name": "enrolment_id", "dataType": "string", "sourceColumn": "enrolment_id"},
          {"name": "student_id", "dataType": "string", "sourceColumn": "student_id"},
          {"name": "department", "dataType": "string", "sourceColumn": "department"},
          {"name": "level", "dataType": "string", "sourceColumn": "level"},
          {"name": "programme", "dataType": "string", "sourceColumn": "programme"},
          {"name": "credits", "dataType": "int64", "sourceColumn": "credits"},
          {"name": "age_at_enrolment", "dataType": "int64", "sourceColumn": "age_at_enrolment"},
          {"name": "avg_score", "dataType": "double", "sourceColumn": "avg_score"},
          {"name": "pass_rate", "dataType": "double", "sourceColumn": "pass_rate"},
          {"name": "had_dropout", "dataType": "int64", "sourceColumn": "had_dropout"},
          {"name": "predicted_dropout", "dataType": "int64", "sourceColumn": "predicted_dropout"},
          {"name": "dropout_probability", "dataType": "double", "sourceColumn": "dropout_probability"},
          {"name": "risk_level", "dataType": "string", "sourceColumn": "risk_level"},
          {"name": "scored_at", "dataType": "dateTime", "sourceColumn": "scored_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_predictions",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Predictions", "expression": "COUNTROWS(gold_ml_predictions)", "formatString": "#,##0"},
          {"name": "Predicted Dropouts", "expression": "SUM(gold_ml_predictions[predicted_dropout])", "formatString": "#,##0"},
          {"name": "Actual Dropouts", "expression": "SUM(gold_ml_predictions[had_dropout])", "formatString": "#,##0"},
          {"name": "Avg Dropout Probability", "expression": "AVERAGE(gold_ml_predictions[dropout_probability])", "formatString": "0.0%"},
          {"name": "Predicted Dropout Rate %", "expression": "DIVIDE(SUM(gold_ml_predictions[predicted_dropout]), COUNTROWS(gold_ml_predictions), 0) * 100", "formatString": "0.0"},
          {"name": "Avg Assessment Score", "expression": "AVERAGE(gold_ml_predictions[avg_score])", "formatString": "0.0"}
        ]
      },
      {
        "name": "gold_ml_summary",
        "columns": [
          {"name": "department", "dataType": "string", "sourceColumn": "department"},
          {"name": "total_enrolments", "dataType": "int64", "sourceColumn": "total_enrolments"},
          {"name": "predicted_dropout_count", "dataType": "int64", "sourceColumn": "predicted_dropout_count"},
          {"name": "actual_dropout_count", "dataType": "int64", "sourceColumn": "actual_dropout_count"},
          {"name": "avg_dropout_probability", "dataType": "double", "sourceColumn": "avg_dropout_probability"},
          {"name": "avg_assessment_score", "dataType": "double", "sourceColumn": "avg_assessment_score"},
          {"name": "avg_age", "dataType": "double", "sourceColumn": "avg_age"},
          {"name": "dropout_rate", "dataType": "double", "sourceColumn": "dropout_rate"},
          {"name": "overall_risk", "dataType": "string", "sourceColumn": "overall_risk"},
          {"name": "summary_timestamp", "dataType": "dateTime", "sourceColumn": "summary_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_summary",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Departments", "expression": "COUNTROWS(gold_ml_summary)", "formatString": "0"},
          {"name": "Avg Dropout Risk", "expression": "AVERAGE(gold_ml_summary[avg_dropout_probability])", "formatString": "0.0%"},
          {"name": "Avg Dropout Rate", "expression": "AVERAGE(gold_ml_summary[dropout_rate])", "formatString": "0.0"},
          {"name": "Total Predicted Dropouts", "expression": "SUM(gold_ml_summary[predicted_dropout_count])", "formatString": "#,##0"},
          {"name": "High Risk Departments", "expression": "CALCULATE(COUNTROWS(gold_ml_summary), gold_ml_summary[overall_risk] = \"high\") + 0", "formatString": "0"}
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_predictions_summary",
        "fromTable": "gold_ml_predictions",
        "fromColumn": "department",
        "toTable": "gold_ml_summary",
        "toColumn": "department",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DatabaseQuery",
        "kind": "m",
        "expression": "let\n    database = Sql.Database(\"{{SQL_ENDPOINT}}\", \"{{LAKEHOUSE_NAME}}\")\nin\n    database"
      }
    ],
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"gold_ml_model_metrics\",\"gold_ml_feature_importance\",\"gold_ml_predictions\",\"gold_ml_summary\"]"}
    ]
  }
}
