{
  "compatibilityLevel": 1604,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "gold_ml_model_metrics",
        "columns": [
          {"name": "demo_id", "dataType": "string", "sourceColumn": "demo_id"},
          {"name": "use_case", "dataType": "string", "sourceColumn": "use_case"},
          {"name": "model_type", "dataType": "string", "sourceColumn": "model_type"},
          {"name": "feature_count", "dataType": "int64", "sourceColumn": "feature_count"},
          {"name": "train_rows", "dataType": "int64", "sourceColumn": "train_rows"},
          {"name": "test_rows", "dataType": "int64", "sourceColumn": "test_rows"},
          {"name": "auc_roc", "dataType": "double", "sourceColumn": "auc_roc"},
          {"name": "accuracy", "dataType": "double", "sourceColumn": "accuracy"},
          {"name": "f1_score", "dataType": "double", "sourceColumn": "f1_score"},
          {"name": "trained_at", "dataType": "dateTime", "sourceColumn": "trained_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_model_metrics",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Model AUC", "expression": "AVERAGE(gold_ml_model_metrics[auc_roc])", "formatString": "0.000"},
          {"name": "Model Accuracy", "expression": "AVERAGE(gold_ml_model_metrics[accuracy])", "formatString": "0.0%"},
          {"name": "F1 Score", "expression": "AVERAGE(gold_ml_model_metrics[f1_score])", "formatString": "0.000"},
          {"name": "Feature Count", "expression": "MAX(gold_ml_model_metrics[feature_count])", "formatString": "0"},
          {"name": "Training Rows", "expression": "MAX(gold_ml_model_metrics[train_rows])", "formatString": "#,##0"},
          {"name": "Test Rows", "expression": "MAX(gold_ml_model_metrics[test_rows])", "formatString": "#,##0"}
        ]
      },
      {
        "name": "gold_ml_feature_importance",
        "columns": [
          {"name": "feature", "dataType": "string", "sourceColumn": "feature"},
          {"name": "importance", "dataType": "double", "sourceColumn": "importance"},
          {"name": "model_timestamp", "dataType": "dateTime", "sourceColumn": "model_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_feature_importance",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Importance", "expression": "SUM(gold_ml_feature_importance[importance])", "formatString": "0.0000"}
        ]
      },
      {
        "name": "gold_ml_predictions",
        "columns": [
          {"name": "delivery_id", "dataType": "string", "sourceColumn": "delivery_id"},
          {"name": "vehicle_id", "dataType": "string", "sourceColumn": "vehicle_id"},
          {"name": "route_id", "dataType": "string", "sourceColumn": "route_id"},
          {"name": "vehicle_type", "dataType": "string", "sourceColumn": "vehicle_type"},
          {"name": "depot", "dataType": "string", "sourceColumn": "depot"},
          {"name": "route_type", "dataType": "string", "sourceColumn": "route_type"},
          {"name": "distance_km", "dataType": "double", "sourceColumn": "distance_km"},
          {"name": "load_utilisation", "dataType": "double", "sourceColumn": "load_utilisation"},
          {"name": "planned_duration_hrs", "dataType": "double", "sourceColumn": "planned_duration_hrs"},
          {"name": "had_late", "dataType": "int64", "sourceColumn": "had_late"},
          {"name": "predicted_late", "dataType": "int64", "sourceColumn": "predicted_late"},
          {"name": "delay_probability", "dataType": "double", "sourceColumn": "delay_probability"},
          {"name": "risk_level", "dataType": "string", "sourceColumn": "risk_level"},
          {"name": "scored_at", "dataType": "dateTime", "sourceColumn": "scored_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_predictions",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Predictions", "expression": "COUNTROWS(gold_ml_predictions)", "formatString": "#,##0"},
          {"name": "Predicted Late", "expression": "SUM(gold_ml_predictions[predicted_late])", "formatString": "#,##0"},
          {"name": "Actual Late", "expression": "SUM(gold_ml_predictions[had_late])", "formatString": "#,##0"},
          {"name": "Avg Delay Probability", "expression": "AVERAGE(gold_ml_predictions[delay_probability])", "formatString": "0.0%"},
          {"name": "Predicted Late Rate %", "expression": "DIVIDE(SUM(gold_ml_predictions[predicted_late]), COUNTROWS(gold_ml_predictions), 0) * 100", "formatString": "0.0"},
          {"name": "Avg Distance (km)", "expression": "AVERAGE(gold_ml_predictions[distance_km])", "formatString": "#,##0"}
        ]
      },
      {
        "name": "gold_ml_summary",
        "columns": [
          {"name": "depot", "dataType": "string", "sourceColumn": "depot"},
          {"name": "total_deliveries", "dataType": "int64", "sourceColumn": "total_deliveries"},
          {"name": "predicted_late_count", "dataType": "int64", "sourceColumn": "predicted_late_count"},
          {"name": "actual_late_count", "dataType": "int64", "sourceColumn": "actual_late_count"},
          {"name": "avg_delay_probability", "dataType": "double", "sourceColumn": "avg_delay_probability"},
          {"name": "avg_distance_km", "dataType": "double", "sourceColumn": "avg_distance_km"},
          {"name": "avg_load_utilisation", "dataType": "double", "sourceColumn": "avg_load_utilisation"},
          {"name": "late_rate", "dataType": "double", "sourceColumn": "late_rate"},
          {"name": "overall_risk", "dataType": "string", "sourceColumn": "overall_risk"},
          {"name": "summary_timestamp", "dataType": "dateTime", "sourceColumn": "summary_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_summary",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Depots", "expression": "COUNTROWS(gold_ml_summary)", "formatString": "0"},
          {"name": "Avg Delay Risk", "expression": "AVERAGE(gold_ml_summary[avg_delay_probability])", "formatString": "0.0%"},
          {"name": "Avg Late Rate", "expression": "AVERAGE(gold_ml_summary[late_rate])", "formatString": "0.0"},
          {"name": "Total Predicted Late", "expression": "SUM(gold_ml_summary[predicted_late_count])", "formatString": "#,##0"},
          {"name": "High Risk Depots", "expression": "CALCULATE(COUNTROWS(gold_ml_summary), gold_ml_summary[overall_risk] = \"high\") + 0", "formatString": "0"}
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_predictions_summary",
        "fromTable": "gold_ml_predictions",
        "fromColumn": "depot",
        "toTable": "gold_ml_summary",
        "toColumn": "depot",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DatabaseQuery",
        "kind": "m",
        "expression": "let\n    database = Sql.Database(\"{{SQL_ENDPOINT}}\", \"{{LAKEHOUSE_NAME}}\")\nin\n    database"
      }
    ],
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"gold_ml_model_metrics\",\"gold_ml_feature_importance\",\"gold_ml_predictions\",\"gold_ml_summary\"]"}
    ]
  }
}
