{
  "compatibilityLevel": 1604,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "gold_ml_model_metrics",
        "columns": [
          {"name": "demo_id", "dataType": "string", "sourceColumn": "demo_id"},
          {"name": "use_case", "dataType": "string", "sourceColumn": "use_case"},
          {"name": "model_type", "dataType": "string", "sourceColumn": "model_type"},
          {"name": "feature_count", "dataType": "int64", "sourceColumn": "feature_count"},
          {"name": "train_rows", "dataType": "int64", "sourceColumn": "train_rows"},
          {"name": "test_rows", "dataType": "int64", "sourceColumn": "test_rows"},
          {"name": "auc_roc", "dataType": "double", "sourceColumn": "auc_roc"},
          {"name": "accuracy", "dataType": "double", "sourceColumn": "accuracy"},
          {"name": "f1_score", "dataType": "double", "sourceColumn": "f1_score"},
          {"name": "trained_at", "dataType": "dateTime", "sourceColumn": "trained_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_model_metrics",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Model AUC", "expression": "AVERAGE(gold_ml_model_metrics[auc_roc])", "formatString": "0.000"},
          {"name": "Model Accuracy", "expression": "AVERAGE(gold_ml_model_metrics[accuracy])", "formatString": "0.0%"},
          {"name": "F1 Score", "expression": "AVERAGE(gold_ml_model_metrics[f1_score])", "formatString": "0.000"},
          {"name": "Feature Count", "expression": "MAX(gold_ml_model_metrics[feature_count])", "formatString": "0"},
          {"name": "Training Rows", "expression": "MAX(gold_ml_model_metrics[train_rows])", "formatString": "#,##0"},
          {"name": "Test Rows", "expression": "MAX(gold_ml_model_metrics[test_rows])", "formatString": "#,##0"}
        ]
      },
      {
        "name": "gold_ml_feature_importance",
        "columns": [
          {"name": "feature", "dataType": "string", "sourceColumn": "feature"},
          {"name": "importance", "dataType": "double", "sourceColumn": "importance"},
          {"name": "model_timestamp", "dataType": "dateTime", "sourceColumn": "model_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_feature_importance",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Importance", "expression": "SUM(gold_ml_feature_importance[importance])", "formatString": "0.0000"}
        ]
      },
      {
        "name": "gold_ml_predictions",
        "columns": [
          {"name": "admission_id", "dataType": "string", "sourceColumn": "admission_id"},
          {"name": "patient_id", "dataType": "string", "sourceColumn": "patient_id"},
          {"name": "department", "dataType": "string", "sourceColumn": "department"},
          {"name": "admission_type", "dataType": "string", "sourceColumn": "admission_type"},
          {"name": "insurance_type", "dataType": "string", "sourceColumn": "insurance_type"},
          {"name": "age_group", "dataType": "string", "sourceColumn": "age_group"},
          {"name": "los_bucket", "dataType": "string", "sourceColumn": "los_bucket"},
          {"name": "length_of_stay_days", "dataType": "int64", "sourceColumn": "length_of_stay_days"},
          {"name": "abnormal_vital_count", "dataType": "int64", "sourceColumn": "abnormal_vital_count"},
          {"name": "had_readmission", "dataType": "int64", "sourceColumn": "had_readmission"},
          {"name": "predicted_readmission", "dataType": "int64", "sourceColumn": "predicted_readmission"},
          {"name": "readmission_probability", "dataType": "double", "sourceColumn": "readmission_probability"},
          {"name": "risk_level", "dataType": "string", "sourceColumn": "risk_level"},
          {"name": "scored_at", "dataType": "dateTime", "sourceColumn": "scored_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_predictions",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Predictions", "expression": "COUNTROWS(gold_ml_predictions)", "formatString": "#,##0"},
          {"name": "Predicted Readmissions", "expression": "SUM(gold_ml_predictions[predicted_readmission])", "formatString": "#,##0"},
          {"name": "Actual Readmissions", "expression": "SUM(gold_ml_predictions[had_readmission])", "formatString": "#,##0"},
          {"name": "Avg Readmission Probability", "expression": "AVERAGE(gold_ml_predictions[readmission_probability])", "formatString": "0.0%"},
          {"name": "Predicted Readmission Rate %", "expression": "DIVIDE(SUM(gold_ml_predictions[predicted_readmission]), COUNTROWS(gold_ml_predictions), 0) * 100", "formatString": "0.0"},
          {"name": "Avg Length of Stay", "expression": "AVERAGE(gold_ml_predictions[length_of_stay_days])", "formatString": "0.0"}
        ]
      },
      {
        "name": "gold_ml_summary",
        "columns": [
          {"name": "department", "dataType": "string", "sourceColumn": "department"},
          {"name": "total_admissions", "dataType": "int64", "sourceColumn": "total_admissions"},
          {"name": "predicted_readmission_count", "dataType": "int64", "sourceColumn": "predicted_readmission_count"},
          {"name": "actual_readmission_count", "dataType": "int64", "sourceColumn": "actual_readmission_count"},
          {"name": "avg_readmission_probability", "dataType": "double", "sourceColumn": "avg_readmission_probability"},
          {"name": "avg_length_of_stay", "dataType": "double", "sourceColumn": "avg_length_of_stay"},
          {"name": "avg_abnormal_vitals", "dataType": "double", "sourceColumn": "avg_abnormal_vitals"},
          {"name": "readmission_rate", "dataType": "double", "sourceColumn": "readmission_rate"},
          {"name": "overall_risk", "dataType": "string", "sourceColumn": "overall_risk"},
          {"name": "summary_timestamp", "dataType": "dateTime", "sourceColumn": "summary_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_summary",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Departments", "expression": "COUNTROWS(gold_ml_summary)", "formatString": "0"},
          {"name": "Avg Readmission Risk", "expression": "AVERAGE(gold_ml_summary[avg_readmission_probability])", "formatString": "0.0%"},
          {"name": "Avg Readmission Rate", "expression": "AVERAGE(gold_ml_summary[readmission_rate])", "formatString": "0.0"},
          {"name": "Total Predicted Readmissions", "expression": "SUM(gold_ml_summary[predicted_readmission_count])", "formatString": "#,##0"},
          {"name": "High Risk Departments", "expression": "CALCULATE(COUNTROWS(gold_ml_summary), gold_ml_summary[overall_risk] = \"high\") + 0", "formatString": "0"}
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_predictions_summary",
        "fromTable": "gold_ml_predictions",
        "fromColumn": "department",
        "toTable": "gold_ml_summary",
        "toColumn": "department",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DatabaseQuery",
        "kind": "m",
        "expression": "let\n    database = Sql.Database(\"{{SQL_ENDPOINT}}\", \"{{LAKEHOUSE_NAME}}\")\nin\n    database"
      }
    ],
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"gold_ml_model_metrics\",\"gold_ml_feature_importance\",\"gold_ml_predictions\",\"gold_ml_summary\"]"}
    ]
  }
}
