{
  "compatibilityLevel": 1604,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "gold_ml_model_metrics",
        "columns": [
          {"name": "demo_id", "dataType": "string", "sourceColumn": "demo_id"},
          {"name": "use_case", "dataType": "string", "sourceColumn": "use_case"},
          {"name": "model_type", "dataType": "string", "sourceColumn": "model_type"},
          {"name": "feature_count", "dataType": "int64", "sourceColumn": "feature_count"},
          {"name": "train_rows", "dataType": "int64", "sourceColumn": "train_rows"},
          {"name": "test_rows", "dataType": "int64", "sourceColumn": "test_rows"},
          {"name": "auc_roc", "dataType": "double", "sourceColumn": "auc_roc"},
          {"name": "accuracy", "dataType": "double", "sourceColumn": "accuracy"},
          {"name": "f1_score", "dataType": "double", "sourceColumn": "f1_score"},
          {"name": "trained_at", "dataType": "dateTime", "sourceColumn": "trained_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_model_metrics",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Model AUC", "expression": "AVERAGE(gold_ml_model_metrics[auc_roc])", "formatString": "0.000"},
          {"name": "Model Accuracy", "expression": "AVERAGE(gold_ml_model_metrics[accuracy])", "formatString": "0.0%"},
          {"name": "F1 Score", "expression": "AVERAGE(gold_ml_model_metrics[f1_score])", "formatString": "0.000"},
          {"name": "Feature Count", "expression": "MAX(gold_ml_model_metrics[feature_count])", "formatString": "0"},
          {"name": "Training Rows", "expression": "MAX(gold_ml_model_metrics[train_rows])", "formatString": "#,##0"},
          {"name": "Test Rows", "expression": "MAX(gold_ml_model_metrics[test_rows])", "formatString": "#,##0"}
        ]
      },
      {
        "name": "gold_ml_feature_importance",
        "columns": [
          {"name": "feature", "dataType": "string", "sourceColumn": "feature"},
          {"name": "importance", "dataType": "double", "sourceColumn": "importance"},
          {"name": "model_timestamp", "dataType": "dateTime", "sourceColumn": "model_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_feature_importance",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Importance", "expression": "SUM(gold_ml_feature_importance[importance])", "formatString": "0.0000"}
        ]
      },
      {
        "name": "gold_ml_predictions",
        "columns": [
          {"name": "task_id", "dataType": "string", "sourceColumn": "task_id"},
          {"name": "project_id", "dataType": "string", "sourceColumn": "project_id"},
          {"name": "assigned_subcontractor_id", "dataType": "string", "sourceColumn": "assigned_subcontractor_id"},
          {"name": "sub_trade", "dataType": "string", "sourceColumn": "sub_trade"},
          {"name": "task_name", "dataType": "string", "sourceColumn": "task_name"},
          {"name": "project_type", "dataType": "string", "sourceColumn": "project_type"},
          {"name": "planned_duration_days", "dataType": "int64", "sourceColumn": "planned_duration_days"},
          {"name": "sub_rating", "dataType": "double", "sourceColumn": "sub_rating"},
          {"name": "had_delay", "dataType": "int64", "sourceColumn": "had_delay"},
          {"name": "predicted_delay", "dataType": "int64", "sourceColumn": "predicted_delay"},
          {"name": "delay_probability", "dataType": "double", "sourceColumn": "delay_probability"},
          {"name": "risk_level", "dataType": "string", "sourceColumn": "risk_level"},
          {"name": "scored_at", "dataType": "dateTime", "sourceColumn": "scored_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_predictions",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Predictions", "expression": "COUNTROWS(gold_ml_predictions)", "formatString": "#,##0"},
          {"name": "Predicted Delays", "expression": "SUM(gold_ml_predictions[predicted_delay])", "formatString": "#,##0"},
          {"name": "Actual Delays", "expression": "SUM(gold_ml_predictions[had_delay])", "formatString": "#,##0"},
          {"name": "Avg Delay Probability", "expression": "AVERAGE(gold_ml_predictions[delay_probability])", "formatString": "0.0%"},
          {"name": "Predicted Delay Rate %", "expression": "DIVIDE(SUM(gold_ml_predictions[predicted_delay]), COUNTROWS(gold_ml_predictions), 0) * 100", "formatString": "0.0"},
          {"name": "Avg Planned Duration (days)", "expression": "AVERAGE(gold_ml_predictions[planned_duration_days])", "formatString": "0.0"}
        ]
      },
      {
        "name": "gold_ml_summary",
        "columns": [
          {"name": "trade", "dataType": "string", "sourceColumn": "trade"},
          {"name": "total_tasks", "dataType": "int64", "sourceColumn": "total_tasks"},
          {"name": "predicted_delay_count", "dataType": "int64", "sourceColumn": "predicted_delay_count"},
          {"name": "actual_delay_count", "dataType": "int64", "sourceColumn": "actual_delay_count"},
          {"name": "avg_delay_probability", "dataType": "double", "sourceColumn": "avg_delay_probability"},
          {"name": "avg_duration_days", "dataType": "double", "sourceColumn": "avg_duration_days"},
          {"name": "avg_sub_rating", "dataType": "double", "sourceColumn": "avg_sub_rating"},
          {"name": "delay_rate", "dataType": "double", "sourceColumn": "delay_rate"},
          {"name": "overall_risk", "dataType": "string", "sourceColumn": "overall_risk"},
          {"name": "summary_timestamp", "dataType": "dateTime", "sourceColumn": "summary_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_summary",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Trades", "expression": "COUNTROWS(gold_ml_summary)", "formatString": "0"},
          {"name": "Avg Delay Risk", "expression": "AVERAGE(gold_ml_summary[avg_delay_probability])", "formatString": "0.0%"},
          {"name": "Avg Delay Rate", "expression": "AVERAGE(gold_ml_summary[delay_rate])", "formatString": "0.0"},
          {"name": "Total Predicted Delays", "expression": "SUM(gold_ml_summary[predicted_delay_count])", "formatString": "#,##0"},
          {"name": "High Risk Trades", "expression": "CALCULATE(COUNTROWS(gold_ml_summary), gold_ml_summary[overall_risk] = \"high\") + 0", "formatString": "0"}
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_predictions_summary",
        "fromTable": "gold_ml_predictions",
        "fromColumn": "sub_trade",
        "toTable": "gold_ml_summary",
        "toColumn": "trade",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DatabaseQuery",
        "kind": "m",
        "expression": "let\n    database = Sql.Database(\"{{SQL_ENDPOINT}}\", \"{{LAKEHOUSE_NAME}}\")\nin\n    database"
      }
    ],
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"gold_ml_model_metrics\",\"gold_ml_feature_importance\",\"gold_ml_predictions\",\"gold_ml_summary\"]"}
    ]
  }
}
