{
  "compatibilityLevel": 1604,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "gold_ml_model_metrics",
        "columns": [
          {"name": "demo_id", "dataType": "string", "sourceColumn": "demo_id"},
          {"name": "use_case", "dataType": "string", "sourceColumn": "use_case"},
          {"name": "model_type", "dataType": "string", "sourceColumn": "model_type"},
          {"name": "feature_count", "dataType": "int64", "sourceColumn": "feature_count"},
          {"name": "train_rows", "dataType": "int64", "sourceColumn": "train_rows"},
          {"name": "test_rows", "dataType": "int64", "sourceColumn": "test_rows"},
          {"name": "auc_roc", "dataType": "double", "sourceColumn": "auc_roc"},
          {"name": "accuracy", "dataType": "double", "sourceColumn": "accuracy"},
          {"name": "f1_score", "dataType": "double", "sourceColumn": "f1_score"},
          {"name": "trained_at", "dataType": "dateTime", "sourceColumn": "trained_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_model_metrics",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Model AUC", "expression": "AVERAGE(gold_ml_model_metrics[auc_roc])", "formatString": "0.000"},
          {"name": "Model Accuracy", "expression": "AVERAGE(gold_ml_model_metrics[accuracy])", "formatString": "0.0%"},
          {"name": "F1 Score", "expression": "AVERAGE(gold_ml_model_metrics[f1_score])", "formatString": "0.000"},
          {"name": "Feature Count", "expression": "MAX(gold_ml_model_metrics[feature_count])", "formatString": "0"},
          {"name": "Training Rows", "expression": "MAX(gold_ml_model_metrics[train_rows])", "formatString": "#,##0"},
          {"name": "Test Rows", "expression": "MAX(gold_ml_model_metrics[test_rows])", "formatString": "#,##0"}
        ]
      },
      {
        "name": "gold_ml_feature_importance",
        "columns": [
          {"name": "feature", "dataType": "string", "sourceColumn": "feature"},
          {"name": "importance", "dataType": "double", "sourceColumn": "importance"},
          {"name": "model_timestamp", "dataType": "dateTime", "sourceColumn": "model_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_feature_importance",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Importance", "expression": "SUM(gold_ml_feature_importance[importance])", "formatString": "0.0000"}
        ]
      },
      {
        "name": "gold_ml_predictions",
        "columns": [
          {"name": "booking_id", "dataType": "string", "sourceColumn": "booking_id"},
          {"name": "guest_id", "dataType": "string", "sourceColumn": "guest_id"},
          {"name": "property_id", "dataType": "string", "sourceColumn": "property_id"},
          {"name": "channel", "dataType": "string", "sourceColumn": "channel"},
          {"name": "room_type", "dataType": "string", "sourceColumn": "room_type"},
          {"name": "loyalty_tier", "dataType": "string", "sourceColumn": "loyalty_tier"},
          {"name": "room_rate", "dataType": "double", "sourceColumn": "room_rate"},
          {"name": "lead_time_days", "dataType": "int64", "sourceColumn": "lead_time_days"},
          {"name": "nights", "dataType": "int64", "sourceColumn": "nights"},
          {"name": "had_cancel", "dataType": "int64", "sourceColumn": "had_cancel"},
          {"name": "predicted_cancel", "dataType": "int64", "sourceColumn": "predicted_cancel"},
          {"name": "cancel_probability", "dataType": "double", "sourceColumn": "cancel_probability"},
          {"name": "risk_level", "dataType": "string", "sourceColumn": "risk_level"},
          {"name": "scored_at", "dataType": "dateTime", "sourceColumn": "scored_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_predictions",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Predictions", "expression": "COUNTROWS(gold_ml_predictions)", "formatString": "#,##0"},
          {"name": "Predicted Cancellations", "expression": "SUM(gold_ml_predictions[predicted_cancel])", "formatString": "#,##0"},
          {"name": "Actual Cancellations", "expression": "SUM(gold_ml_predictions[had_cancel])", "formatString": "#,##0"},
          {"name": "Avg Cancel Probability", "expression": "AVERAGE(gold_ml_predictions[cancel_probability])", "formatString": "0.0%"},
          {"name": "Predicted Cancel Rate %", "expression": "DIVIDE(SUM(gold_ml_predictions[predicted_cancel]), COUNTROWS(gold_ml_predictions), 0) * 100", "formatString": "0.0"},
          {"name": "Avg Lead Time (days)", "expression": "AVERAGE(gold_ml_predictions[lead_time_days])", "formatString": "0.0"}
        ]
      },
      {
        "name": "gold_ml_summary",
        "columns": [
          {"name": "channel", "dataType": "string", "sourceColumn": "channel"},
          {"name": "total_bookings", "dataType": "int64", "sourceColumn": "total_bookings"},
          {"name": "predicted_cancel_count", "dataType": "int64", "sourceColumn": "predicted_cancel_count"},
          {"name": "actual_cancel_count", "dataType": "int64", "sourceColumn": "actual_cancel_count"},
          {"name": "avg_cancel_probability", "dataType": "double", "sourceColumn": "avg_cancel_probability"},
          {"name": "avg_room_rate", "dataType": "double", "sourceColumn": "avg_room_rate"},
          {"name": "avg_lead_time_days", "dataType": "double", "sourceColumn": "avg_lead_time_days"},
          {"name": "cancel_rate", "dataType": "double", "sourceColumn": "cancel_rate"},
          {"name": "overall_risk", "dataType": "string", "sourceColumn": "overall_risk"},
          {"name": "summary_timestamp", "dataType": "dateTime", "sourceColumn": "summary_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_summary",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Channels", "expression": "COUNTROWS(gold_ml_summary)", "formatString": "0"},
          {"name": "Avg Cancel Risk", "expression": "AVERAGE(gold_ml_summary[avg_cancel_probability])", "formatString": "0.0%"},
          {"name": "Avg Cancel Rate", "expression": "AVERAGE(gold_ml_summary[cancel_rate])", "formatString": "0.0"},
          {"name": "Total Predicted Cancellations", "expression": "SUM(gold_ml_summary[predicted_cancel_count])", "formatString": "#,##0"},
          {"name": "High Risk Channels", "expression": "CALCULATE(COUNTROWS(gold_ml_summary), gold_ml_summary[overall_risk] = \"high\") + 0", "formatString": "0"}
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_predictions_summary",
        "fromTable": "gold_ml_predictions",
        "fromColumn": "channel",
        "toTable": "gold_ml_summary",
        "toColumn": "channel",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DatabaseQuery",
        "kind": "m",
        "expression": "let\n    database = Sql.Database(\"{{SQL_ENDPOINT}}\", \"{{LAKEHOUSE_NAME}}\")\nin\n    database"
      }
    ],
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"gold_ml_model_metrics\",\"gold_ml_feature_importance\",\"gold_ml_predictions\",\"gold_ml_summary\"]"}
    ]
  }
}
