{
  "compatibilityLevel": 1604,
  "model": {
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "tables": [
      {
        "name": "gold_ml_model_metrics",
        "columns": [
          {"name": "demo_id", "dataType": "string", "sourceColumn": "demo_id"},
          {"name": "use_case", "dataType": "string", "sourceColumn": "use_case"},
          {"name": "model_type", "dataType": "string", "sourceColumn": "model_type"},
          {"name": "feature_count", "dataType": "int64", "sourceColumn": "feature_count"},
          {"name": "train_rows", "dataType": "int64", "sourceColumn": "train_rows"},
          {"name": "test_rows", "dataType": "int64", "sourceColumn": "test_rows"},
          {"name": "auc_roc", "dataType": "double", "sourceColumn": "auc_roc"},
          {"name": "accuracy", "dataType": "double", "sourceColumn": "accuracy"},
          {"name": "f1_score", "dataType": "double", "sourceColumn": "f1_score"},
          {"name": "trained_at", "dataType": "dateTime", "sourceColumn": "trained_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_model_metrics",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Model AUC", "expression": "AVERAGE(gold_ml_model_metrics[auc_roc])", "formatString": "0.000"},
          {"name": "Model Accuracy", "expression": "AVERAGE(gold_ml_model_metrics[accuracy])", "formatString": "0.0%"},
          {"name": "F1 Score", "expression": "AVERAGE(gold_ml_model_metrics[f1_score])", "formatString": "0.000"},
          {"name": "Feature Count", "expression": "MAX(gold_ml_model_metrics[feature_count])", "formatString": "0"},
          {"name": "Training Rows", "expression": "MAX(gold_ml_model_metrics[train_rows])", "formatString": "#,##0"},
          {"name": "Test Rows", "expression": "MAX(gold_ml_model_metrics[test_rows])", "formatString": "#,##0"}
        ]
      },
      {
        "name": "gold_ml_feature_importance",
        "columns": [
          {"name": "feature", "dataType": "string", "sourceColumn": "feature"},
          {"name": "importance", "dataType": "double", "sourceColumn": "importance"},
          {"name": "model_timestamp", "dataType": "dateTime", "sourceColumn": "model_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_feature_importance",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Importance", "expression": "SUM(gold_ml_feature_importance[importance])", "formatString": "0.0000"}
        ]
      },
      {
        "name": "gold_ml_predictions",
        "columns": [
          {"name": "engagement_id", "dataType": "string", "sourceColumn": "engagement_id"},
          {"name": "client_id", "dataType": "string", "sourceColumn": "client_id"},
          {"name": "lead_consultant_id", "dataType": "string", "sourceColumn": "lead_consultant_id"},
          {"name": "practice", "dataType": "string", "sourceColumn": "practice"},
          {"name": "industry", "dataType": "string", "sourceColumn": "industry"},
          {"name": "tier", "dataType": "string", "sourceColumn": "tier"},
          {"name": "budget_gbp", "dataType": "double", "sourceColumn": "budget_gbp"},
          {"name": "headcount", "dataType": "int64", "sourceColumn": "headcount"},
          {"name": "planned_duration_days", "dataType": "int64", "sourceColumn": "planned_duration_days"},
          {"name": "had_overrun", "dataType": "int64", "sourceColumn": "had_overrun"},
          {"name": "predicted_overrun", "dataType": "int64", "sourceColumn": "predicted_overrun"},
          {"name": "overrun_probability", "dataType": "double", "sourceColumn": "overrun_probability"},
          {"name": "risk_level", "dataType": "string", "sourceColumn": "risk_level"},
          {"name": "scored_at", "dataType": "dateTime", "sourceColumn": "scored_at"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_predictions",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Total Predictions", "expression": "COUNTROWS(gold_ml_predictions)", "formatString": "#,##0"},
          {"name": "Predicted Overruns", "expression": "SUM(gold_ml_predictions[predicted_overrun])", "formatString": "#,##0"},
          {"name": "Actual Overruns", "expression": "SUM(gold_ml_predictions[had_overrun])", "formatString": "#,##0"},
          {"name": "Avg Overrun Probability", "expression": "AVERAGE(gold_ml_predictions[overrun_probability])", "formatString": "0.0%"},
          {"name": "Predicted Overrun Rate %", "expression": "DIVIDE(SUM(gold_ml_predictions[predicted_overrun]), COUNTROWS(gold_ml_predictions), 0) * 100", "formatString": "0.0"},
          {"name": "Avg Budget (GBP)", "expression": "AVERAGE(gold_ml_predictions[budget_gbp])", "formatString": "#,##0"}
        ]
      },
      {
        "name": "gold_ml_summary",
        "columns": [
          {"name": "practice", "dataType": "string", "sourceColumn": "practice"},
          {"name": "total_engagements", "dataType": "int64", "sourceColumn": "total_engagements"},
          {"name": "predicted_overrun_count", "dataType": "int64", "sourceColumn": "predicted_overrun_count"},
          {"name": "actual_overrun_count", "dataType": "int64", "sourceColumn": "actual_overrun_count"},
          {"name": "avg_overrun_probability", "dataType": "double", "sourceColumn": "avg_overrun_probability"},
          {"name": "avg_budget_gbp", "dataType": "double", "sourceColumn": "avg_budget_gbp"},
          {"name": "avg_duration_days", "dataType": "double", "sourceColumn": "avg_duration_days"},
          {"name": "overrun_rate", "dataType": "double", "sourceColumn": "overrun_rate"},
          {"name": "overall_risk", "dataType": "string", "sourceColumn": "overall_risk"},
          {"name": "summary_timestamp", "dataType": "dateTime", "sourceColumn": "summary_timestamp"}
        ],
        "partitions": [
          {
            "name": "part0",
            "mode": "directLake",
            "source": {
              "type": "entity",
              "entityName": "gold_ml_summary",
              "schemaName": "dbo",
              "expressionSource": "DatabaseQuery"
            }
          }
        ],
        "measures": [
          {"name": "Practices", "expression": "COUNTROWS(gold_ml_summary)", "formatString": "0"},
          {"name": "Avg Overrun Risk", "expression": "AVERAGE(gold_ml_summary[avg_overrun_probability])", "formatString": "0.0%"},
          {"name": "Avg Overrun Rate", "expression": "AVERAGE(gold_ml_summary[overrun_rate])", "formatString": "0.0"},
          {"name": "Total Predicted Overruns", "expression": "SUM(gold_ml_summary[predicted_overrun_count])", "formatString": "#,##0"},
          {"name": "High Risk Practices", "expression": "CALCULATE(COUNTROWS(gold_ml_summary), gold_ml_summary[overall_risk] = \"high\") + 0", "formatString": "0"}
        ]
      }
    ],
    "relationships": [
      {
        "name": "rel_predictions_summary",
        "fromTable": "gold_ml_predictions",
        "fromColumn": "practice",
        "toTable": "gold_ml_summary",
        "toColumn": "practice",
        "crossFilteringBehavior": "oneDirection"
      }
    ],
    "expressions": [
      {
        "name": "DatabaseQuery",
        "kind": "m",
        "expression": "let\n    database = Sql.Database(\"{{SQL_ENDPOINT}}\", \"{{LAKEHOUSE_NAME}}\")\nin\n    database"
      }
    ],
    "annotations": [
      {"name": "PBI_QueryOrder", "value": "[\"gold_ml_model_metrics\",\"gold_ml_feature_importance\",\"gold_ml_predictions\",\"gold_ml_summary\"]"}
    ]
  }
}
